Pipeline:
  name: pygoat

GitRepo:
  name: pygoat
  gitProvider: github
  path: leapfrogger/pygoat
  branches:
    include: 'master'

artifactoryIntegration: nitin_artifactory

Image:
  sourceRepository: nitin-docker-local

DockerBuild:
  name: pygoatbuild
  dockerImageName: pygoat
  dockerFileName: Dockerfile
  dockerFileLocation: '.'
  dockerImageTag: ${run_number}

DockerPush:
  name: pygoatpush
  targetRepository: nitin-docker-local

BuildInfo:
  autoPublishBuildInfo: true
  name: pygoatBuildInfo
