Pipeline:
  name: pygoat

GitRepo:
  name: pygoat
  gitProvider: nitin_github
  path: leapfrogger/pygoat
  branches:
    include: 'master'

artifactoryIntegration: nitin_artifactory

Image:
  sourceRepository: nitin-docker-local

DockerBuild:
  name: pygoatbuild
  affinityGroup: docker_group
  dockerImageName: pygoat
  dockerFileName: Dockerfile
  dockerFileLocation: '.'
  dockerImageTag: ${run_number}

DockerPush:
  name: pygoatpush
  affinityGroup: docker_group
  targetRepository: nitin-docker-local
  integrations:
    - name: nitin_artifactory
  inputSteps:
    - name: pygoatbuild

BuildInfo:
  autoPublishBuildInfo: true
  name: pygoatBuildInfo
