Pipeline:
  name: pygoat

GitRepo:
  name: pygoat
  gitProvider: nitin_github
  path: leapfrogger/pygoat
  branches:
    include: 'master'

artifactoryIntegration: nitin_artifactory
artifactoryUrl: pipelines.soleng.jfrog.io

Image:
  sourceRepository: nitin-docker-local
  imageName: pygoat

DockerBuild:
  name: pygoatbuild
  affinityGroup: docker_group
  dockerImageName: "{{ .Values.artifactoryUrl }}/{{ .Values.Image.sourceRepository }}/{{ .Values.Image.imageName }}"
  dockerFileName: Dockerfile
  dockerImageTag: ${run_number}
  dockerFileLocation: .

DockerPush:
  name: pygoatpush
  affinityGroup: docker_group
  targetRepository: nitin-docker-local
  integrations:
    - name: nitin_artifactory
  inputSteps:
    - name: pygoatbuild

BuildInfo:
  autoPublishBuildInfo: true
  name: pygoatBuildInfo
